### PR TITLE
[WEEK15]_전서윤

### PR DESCRIPTION
**Pull request by wlrmadbs**
[강의요약]
[[WEEK15]_전서윤 .pdf](https://github.com/user-attachments/files/15861272/WEEK15._.pdf)

[캐글 필사]
https://colab.research.google.com/#fileId=https%3A//storage.googleapis.com/kaggle-colab-exported-notebooks/week15-f4251469-33c2-44ea-b7b3-52983d0c57b6.ipynb%3FX-Goog-Algorithm%3DGOOG4-RSA-SHA256%26X-Goog-Credential%3Dgcp-kaggle-com%2540kaggle-161607.iam.gserviceaccount.com/20240618/auto/storage/goog4_request%26X-Goog-Date%3D20240618T025024Z%26X-Goog-Expires%3D259200%26X-Goog-SignedHeaders%3Dhost%26X-Goog-Signature%3D693fa761bd46ab4386e14b9acb8216ef2821ac34a9eddb32ae8b0589bc6d8f1a6117e5adc55d7b8c63b5e972adc33036068564c6ca674a23eda2f52533ddd2e4b806467c0f6a1a594c741018db780dd3a0091cba1044a201fe1277f3837551e0abd4b530843df1ccfc522a86691901e356c643f6537d0af1769eb8b4bd119c1a165d884be250737c53fae2e01e76e39085958ed575f950d93c1294d14096c250ccccde6624aff9b68c7040d735f1c9febf6f5beb0032669c4c8c811d83e3753d5faebe887edcf214808b1d3d4aceac77f3b496bcca096379516c977a05671ed4e356a4a3b381c76faaa51ccb9b8d1320d95f51b86be20861769dcc988d789c9d

### CODE REVIEW

**Comment by bsoiyou** [comment]
캐글 필사 과제 링크 확인이 안됩니다...! 수정해서 다시 올려주세요!

**Comment by wlrmadbs** [comment]
다시 Save version 하고 링크 재첨부했습니다 ..! 다시 확인 부탁드려요

**Comment by bsoiyou** [comment]
이전과 동일하게 "We can't find that page" 로 뜨네요ㅠㅠ ipynb 파일을 다운받아서 첨부해주실 수 있을까요?

**Comment by wlrmadbs** [comment]
다시 올렸습니다 ㅠㅠ 다시 한 번 확인 부탁드려요

**Comment by bsoiyou** [comment]
확인했습니다! 감사합니다!

**Pull request closed without merging**
